webtalk_init -webtalk_dir C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_project_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug  3 10:35:50 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d554bd7d-81f1-4a36-810d-14c26e2f8dd1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d33a1d0666d249f9a6eef79fc845d078" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "25" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "120 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "8 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "98" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "41" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "53576_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3928610071 -regid "" -xml C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_project_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_project_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_project_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
