# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-16416-LAPTOP-FC5L956S/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s100fgga676-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/Reg.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/alu.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/buf_8.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/cmp.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/flp.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/mux.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/mux_8.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/mux_idb.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/pc_cnt.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/S4P.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/counter.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/mux_6.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/mux1_8.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/map_rom.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/mov_decoder.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/uop_rom.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/cpu_project.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/imports/EEE3163-S4P/buf.vhd
      C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.srcs/sources_1/new/adr_reg.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top S4P
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/ilyou/OneDrive/문서/GitHub/EEE3163-S4P/project_cpu/project_cpu.runs/synth_1/.Xil/Vivado-16416-LAPTOP-FC5L956S/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
